# Spawn AI-test chunk 2/8: Byron, Blaine, Volkner
# Generated by ops/gen_aitest_gyms.py — do not edit by hand.
# Cleanup all: /function server:aitest/cleanup

kill @e[type=rctmod:trainer,tag=aitest.chunk2]

# Byron  (+0x)
execute at @s run rctmod trainer summon_persistent aitest_gym_04_byron_pe
execute at @s run tag @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_04_byron_pe"}] add aitest
execute at @s run tag @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_04_byron_pe"}] add aitest.chunk2
execute at @s run tag @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_04_byron_pe"}] add cobblemon_bridge.level_cap.50
execute at @s run data merge entity @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_04_byron_pe"}] {Invulnerable:1b,PersistenceRequired:1b}
execute at @s positioned ^0 ^ ^ run tp @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_04_byron_pe"}] ~ ~ ~

# Blaine  (+3x)
execute at @s run rctmod trainer summon_persistent aitest_gym_05_blaine_pe
execute at @s run tag @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_05_blaine_pe"}] add aitest
execute at @s run tag @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_05_blaine_pe"}] add aitest.chunk2
execute at @s run tag @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_05_blaine_pe"}] add cobblemon_bridge.level_cap.50
execute at @s run data merge entity @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_05_blaine_pe"}] {Invulnerable:1b,PersistenceRequired:1b}
execute at @s positioned ^3 ^ ^ run tp @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_05_blaine_pe"}] ~ ~ ~

# Volkner  (+6x)
execute at @s run rctmod trainer summon_persistent aitest_gym_06_volkner_pe
execute at @s run tag @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_06_volkner_pe"}] add aitest
execute at @s run tag @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_06_volkner_pe"}] add aitest.chunk2
execute at @s run tag @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_06_volkner_pe"}] add cobblemon_bridge.level_cap.50
execute at @s run data merge entity @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_06_volkner_pe"}] {Invulnerable:1b,PersistenceRequired:1b}
execute at @s positioned ^6 ^ ^ run tp @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_06_volkner_pe"}] ~ ~ ~

tellraw @s [{"text":"§a✓ Chunk 2/8: Byron, Blaine, Volkner","bold":true},{"text":"\n§7Next: §f/function server:aitest/spawn_3"},{"text":"\n§7Cleanup: §f/function server:aitest/cleanup"}]
