# Spawn [pe] variants of ALL gym leaders at caller's position, 3 blocks apart along +X.
# Generated by ops/gen_aitest_gyms.py — do not edit by hand.
# Cleanup: /function server:aitest/cleanup

kill @e[type=rctmod:trainer,tag=aitest.variant.pe_all]

# AI Test [pe]: Clay  (+0x)
execute at @s positioned ^0 ^ ^ run rctmod trainer summon_persistent aitest_gym_01_clay_pe
execute at @s positioned ^0 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_01_clay_pe"}] add aitest
execute at @s positioned ^0 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_01_clay_pe"}] add aitest.variant.pe_all
execute at @s positioned ^0 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_01_clay_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Gardenia  (+3x)
execute at @s positioned ^3 ^ ^ run rctmod trainer summon_persistent aitest_gym_02_gardenia_pe
execute at @s positioned ^3 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_02_gardenia_pe"}] add aitest
execute at @s positioned ^3 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_02_gardenia_pe"}] add aitest.variant.pe_all
execute at @s positioned ^3 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_02_gardenia_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Korrina  (+6x)
execute at @s positioned ^6 ^ ^ run rctmod trainer summon_persistent aitest_gym_03_korrina_pe
execute at @s positioned ^6 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_03_korrina_pe"}] add aitest
execute at @s positioned ^6 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_03_korrina_pe"}] add aitest.variant.pe_all
execute at @s positioned ^6 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_03_korrina_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Byron  (+9x)
execute at @s positioned ^9 ^ ^ run rctmod trainer summon_persistent aitest_gym_04_byron_pe
execute at @s positioned ^9 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_04_byron_pe"}] add aitest
execute at @s positioned ^9 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_04_byron_pe"}] add aitest.variant.pe_all
execute at @s positioned ^9 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_04_byron_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Blaine  (+12x)
execute at @s positioned ^12 ^ ^ run rctmod trainer summon_persistent aitest_gym_05_blaine_pe
execute at @s positioned ^12 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_05_blaine_pe"}] add aitest
execute at @s positioned ^12 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_05_blaine_pe"}] add aitest.variant.pe_all
execute at @s positioned ^12 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_05_blaine_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Volkner  (+15x)
execute at @s positioned ^15 ^ ^ run rctmod trainer summon_persistent aitest_gym_06_volkner_pe
execute at @s positioned ^15 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_06_volkner_pe"}] add aitest
execute at @s positioned ^15 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_06_volkner_pe"}] add aitest.variant.pe_all
execute at @s positioned ^15 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_06_volkner_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Crasher Wake  (+18x)
execute at @s positioned ^18 ^ ^ run rctmod trainer summon_persistent aitest_gym_07_crasher_wake_pe
execute at @s positioned ^18 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_07_crasher_wake_pe"}] add aitest
execute at @s positioned ^18 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_07_crasher_wake_pe"}] add aitest.variant.pe_all
execute at @s positioned ^18 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_07_crasher_wake_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Sabrina  (+21x)
execute at @s positioned ^21 ^ ^ run rctmod trainer summon_persistent aitest_gym_08_sabrina_pe
execute at @s positioned ^21 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_08_sabrina_pe"}] add aitest
execute at @s positioned ^21 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_08_sabrina_pe"}] add aitest.variant.pe_all
execute at @s positioned ^21 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_08_sabrina_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Drayden  (+24x)
execute at @s positioned ^24 ^ ^ run rctmod trainer summon_persistent aitest_gym_09_drayden_pe
execute at @s positioned ^24 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_09_drayden_pe"}] add aitest
execute at @s positioned ^24 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_09_drayden_pe"}] add aitest.variant.pe_all
execute at @s positioned ^24 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_09_drayden_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Morty  (+27x)
execute at @s positioned ^27 ^ ^ run rctmod trainer summon_persistent aitest_gym_10_morty_pe
execute at @s positioned ^27 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_10_morty_pe"}] add aitest
execute at @s positioned ^27 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_10_morty_pe"}] add aitest.variant.pe_all
execute at @s positioned ^27 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_10_morty_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Viola  (+30x)
execute at @s positioned ^30 ^ ^ run rctmod trainer summon_persistent aitest_gym_11_viola_pe
execute at @s positioned ^30 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_11_viola_pe"}] add aitest
execute at @s positioned ^30 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_11_viola_pe"}] add aitest.variant.pe_all
execute at @s positioned ^30 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_11_viola_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Cheren  (+33x)
execute at @s positioned ^33 ^ ^ run rctmod trainer summon_persistent aitest_gym_12_cheren_pe
execute at @s positioned ^33 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_12_cheren_pe"}] add aitest
execute at @s positioned ^33 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_12_cheren_pe"}] add aitest.variant.pe_all
execute at @s positioned ^33 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_12_cheren_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Lt. Surge  (+36x)
execute at @s positioned ^36 ^ ^ run rctmod trainer summon_persistent aitest_gym_13_lt_surge_pe
execute at @s positioned ^36 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_13_lt_surge_pe"}] add aitest
execute at @s positioned ^36 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_13_lt_surge_pe"}] add aitest.variant.pe_all
execute at @s positioned ^36 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_13_lt_surge_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Grant  (+39x)
execute at @s positioned ^39 ^ ^ run rctmod trainer summon_persistent aitest_gym_14_grant_pe
execute at @s positioned ^39 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_14_grant_pe"}] add aitest
execute at @s positioned ^39 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_14_grant_pe"}] add aitest.variant.pe_all
execute at @s positioned ^39 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_14_grant_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Skyla  (+42x)
execute at @s positioned ^42 ^ ^ run rctmod trainer summon_persistent aitest_gym_15_skyla_pe
execute at @s positioned ^42 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_15_skyla_pe"}] add aitest
execute at @s positioned ^42 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_15_skyla_pe"}] add aitest.variant.pe_all
execute at @s positioned ^42 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_15_skyla_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Brycen  (+45x)
execute at @s positioned ^45 ^ ^ run rctmod trainer summon_persistent aitest_gym_16_brycen_pe
execute at @s positioned ^45 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_16_brycen_pe"}] add aitest
execute at @s positioned ^45 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_16_brycen_pe"}] add aitest.variant.pe_all
execute at @s positioned ^45 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_16_brycen_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Valerie  (+48x)
execute at @s positioned ^48 ^ ^ run rctmod trainer summon_persistent aitest_gym_17_valerie_pe
execute at @s positioned ^48 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_17_valerie_pe"}] add aitest
execute at @s positioned ^48 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_17_valerie_pe"}] add aitest.variant.pe_all
execute at @s positioned ^48 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_17_valerie_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Marnie  (+51x)
execute at @s positioned ^51 ^ ^ run rctmod trainer summon_persistent aitest_gym_18_marnie_pe
execute at @s positioned ^51 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_18_marnie_pe"}] add aitest
execute at @s positioned ^51 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_18_marnie_pe"}] add aitest.variant.pe_all
execute at @s positioned ^51 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_18_marnie_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Professor Oak  (+54x)
execute at @s positioned ^54 ^ ^ run rctmod trainer summon_persistent aitest_gym_19_oak_pe
execute at @s positioned ^54 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_19_oak_pe"}] add aitest
execute at @s positioned ^54 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_19_oak_pe"}] add aitest.variant.pe_all
execute at @s positioned ^54 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_19_oak_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Elite Four Lorelei  (+57x)
execute at @s positioned ^57 ^ ^ run rctmod trainer summon_persistent aitest_gym_20_lorelei_pe
execute at @s positioned ^57 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_20_lorelei_pe"}] add aitest
execute at @s positioned ^57 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_20_lorelei_pe"}] add aitest.variant.pe_all
execute at @s positioned ^57 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_20_lorelei_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Elite Four Cynthia  (+60x)
execute at @s positioned ^60 ^ ^ run rctmod trainer summon_persistent aitest_gym_21_cynthia_pe
execute at @s positioned ^60 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_21_cynthia_pe"}] add aitest
execute at @s positioned ^60 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_21_cynthia_pe"}] add aitest.variant.pe_all
execute at @s positioned ^60 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_21_cynthia_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Elite Four Agatha  (+63x)
execute at @s positioned ^63 ^ ^ run rctmod trainer summon_persistent aitest_gym_22_agatha_pe
execute at @s positioned ^63 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_22_agatha_pe"}] add aitest
execute at @s positioned ^63 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_22_agatha_pe"}] add aitest.variant.pe_all
execute at @s positioned ^63 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_22_agatha_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Elite Four Lance  (+66x)
execute at @s positioned ^66 ^ ^ run rctmod trainer summon_persistent aitest_gym_23_lance_pe
execute at @s positioned ^66 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_23_lance_pe"}] add aitest
execute at @s positioned ^66 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_23_lance_pe"}] add aitest.variant.pe_all
execute at @s positioned ^66 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_23_lance_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# AI Test [pe]: Pokémon Champion  (+69x)
execute at @s positioned ^69 ^ ^ run rctmod trainer summon_persistent aitest_gym_24_champion_pe
execute at @s positioned ^69 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_24_champion_pe"}] add aitest
execute at @s positioned ^69 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_24_champion_pe"}] add aitest.variant.pe_all
execute at @s positioned ^69 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_24_champion_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

tellraw @s [{"text":"§a✓ Spawned AI Test [pe] row: 24 leaders","bold":true},{"text":"\n§7Cleanup: §f/function server:aitest/cleanup"}]
