# Spawn AI-test chunk 1/8: Clay, Gardenia, Korrina
# Generated by ops/gen_aitest_gyms.py — do not edit by hand.
# Cleanup all: /function server:aitest/cleanup

kill @e[type=rctmod:trainer,tag=aitest.chunk1]

# Clay  (+0x)
execute at @s positioned ^0 ^ ^ run rctmod trainer summon_persistent aitest_gym_01_clay_pe
execute at @s positioned ^0 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_01_clay_pe"}] add aitest
execute at @s positioned ^0 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_01_clay_pe"}] add cobblemon_bridge.level_cap.50
execute at @s positioned ^0 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_01_clay_pe"}] add aitest.chunk1
execute at @s positioned ^0 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_01_clay_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# Gardenia  (+3x)
execute at @s positioned ^3 ^ ^ run rctmod trainer summon_persistent aitest_gym_02_gardenia_pe
execute at @s positioned ^3 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_02_gardenia_pe"}] add aitest
execute at @s positioned ^3 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_02_gardenia_pe"}] add cobblemon_bridge.level_cap.50
execute at @s positioned ^3 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_02_gardenia_pe"}] add aitest.chunk1
execute at @s positioned ^3 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_02_gardenia_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

# Korrina  (+6x)
execute at @s positioned ^6 ^ ^ run rctmod trainer summon_persistent aitest_gym_03_korrina_pe
execute at @s positioned ^6 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_03_korrina_pe"}] add aitest
execute at @s positioned ^6 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_03_korrina_pe"}] add cobblemon_bridge.level_cap.50
execute at @s positioned ^6 ^ ^ run tag @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_03_korrina_pe"}] add aitest.chunk1
execute at @s positioned ^6 ^ ^ run data merge entity @e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_03_korrina_pe"}] {Invulnerable:1b,PersistenceRequired:1b}

tellraw @s [{"text":"§a✓ Chunk 1/8: Clay, Gardenia, Korrina","bold":true},{"text":"\n§7Next: §f/function server:aitest/spawn_2"},{"text":"\n§7Cleanup: §f/function server:aitest/cleanup"}]
