# Spawn AI-test chunk 5/8: Lt. Surge, Grant, Skyla
# Generated by ops/gen_aitest_gyms.py — do not edit by hand.
# Cleanup all: /function server:aitest/cleanup

kill @e[type=rctmod:trainer,tag=aitest.chunk5]

# Lt. Surge  (+0x)
execute at @s run rctmod trainer summon_persistent aitest_gym_13_lt_surge_pe
execute at @s run tag @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_13_lt_surge_pe"}] add aitest
execute at @s run tag @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_13_lt_surge_pe"}] add aitest.chunk5
execute at @s run tag @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_13_lt_surge_pe"}] add cobblemon_bridge.level_cap.50
execute at @s run data merge entity @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_13_lt_surge_pe"}] {Invulnerable:1b,PersistenceRequired:1b}
execute at @s positioned ^0 ^ ^ run tp @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_13_lt_surge_pe"}] ~ ~ ~

# Grant  (+3x)
execute at @s run rctmod trainer summon_persistent aitest_gym_14_grant_pe
execute at @s run tag @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_14_grant_pe"}] add aitest
execute at @s run tag @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_14_grant_pe"}] add aitest.chunk5
execute at @s run tag @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_14_grant_pe"}] add cobblemon_bridge.level_cap.50
execute at @s run data merge entity @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_14_grant_pe"}] {Invulnerable:1b,PersistenceRequired:1b}
execute at @s positioned ^3 ^ ^ run tp @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_14_grant_pe"}] ~ ~ ~

# Skyla  (+6x)
execute at @s run rctmod trainer summon_persistent aitest_gym_15_skyla_pe
execute at @s run tag @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_15_skyla_pe"}] add aitest
execute at @s run tag @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_15_skyla_pe"}] add aitest.chunk5
execute at @s run tag @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_15_skyla_pe"}] add cobblemon_bridge.level_cap.50
execute at @s run data merge entity @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_15_skyla_pe"}] {Invulnerable:1b,PersistenceRequired:1b}
execute at @s positioned ^6 ^ ^ run tp @e[type=rctmod:trainer,limit=1,sort=nearest,nbt={TrainerId:"aitest_gym_15_skyla_pe"}] ~ ~ ~

tellraw @s [{"text":"§a✓ Chunk 5/8: Lt. Surge, Grant, Skyla","bold":true},{"text":"\n§7Next: §f/function server:aitest/spawn_6"},{"text":"\n§7Cleanup: §f/function server:aitest/cleanup"}]
