modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Cobblemon NPC"
authors = ""
description = '''
Minecolonies citizen Pokemon battle progression — profession-themed teams that grow with every loss.
'''

[[mixins]]
config = "cobblemon-npc.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kotlinforforge"
type = "required"
versionRange = "[5.5.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "cobblemon"
type = "required"
versionRange = "[1.7.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecolonies"
type = "required"
versionRange = "[0.0.11,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "cobbledollars"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
