# Auto-generated by quest reward rewrite (round 2 — re-balanced rewards).
playsound minecraft:ui.toast.challenge_complete master @s ~ ~ ~ 1.0 1.2
tellraw @s [{"text": "\n§6§l[Mainline Quest Complete] ", "bold": true},{"text": "First Blood", "color": "white", "bold": true},{"text": "\n§6§l✦ Reward: §e§lCommon Egg", "bold": false},{"text": "\n§e► Next: ", "bold": false},{"text": "Defeat Gym 2: Gardenia §8(Reward: §5Rare Key§8)\n", "color": "white", "bold": false}]
tag @s add cq_reward_egg_common
schedule function server:quests/rewards/_finalize 20t append
