# Auto-generated by quest reward rewrite (round 2 — re-balanced rewards).
playsound minecraft:entity.player.levelup player @s ~ ~ ~ 1.0 1.2
tellraw @s [{"text": "\n§a§l[Quest Complete] ", "bold": true},{"text": "Settler", "color": "white", "bold": true},{"text": "\n§eWelcome home, mayor.", "bold": false},{"text": "\n§6§l✦ Reward: §e§lPoké Healer", "bold": false},{"text": "\n§e► Next: ", "bold": false},{"text": "Continue exploring\n", "color": "white", "bold": false}]
tag @s add cq_reward_item_pokehealer
schedule function server:quests/rewards/_finalize 20t append
