# Auto-generated by quest reward rewrite script. Tag-based dispatcher in _finalize.mcfunction.
playsound minecraft:entity.player.levelup player @s ~ ~ ~ 1.0 1.2
tellraw @s [{"text": "\n§a§l[Quest Complete] ", "bold": true}, {"text": "Veteran", "color": "white", "bold": true}, {"text": "\n§7Reward: §f1 Rare Candy", "bold": false}, {"text": "\n§e► Next: ", "bold": false}, {"text": "Reach 1500 ELO\n", "color": "white", "bold": false}]
tag @s add cq_reward_item_rare_candy
schedule function server:quests/rewards/_finalize 20t append
