# Auto-generated by quest reward rewrite script. Tag-based dispatcher in _finalize.mcfunction.
playsound minecraft:entity.player.levelup player @s ~ ~ ~ 1.0 1.2
tellraw @s [{"text": "\n§a§l[Quest Complete] ", "bold": true}, {"text": "Contender", "color": "white", "bold": true}, {"text": "\n§6§l✦ Reward: §e§lUltra Ball + Hyper Potion", "bold": false}, {"text": "\n§e► Next: ", "bold": false}, {"text": "Reach 1300 ELO §8(Reward: §f1 Rare Candy§8)\n", "color": "white", "bold": false}]
tag @s add cq_reward_item_ranked_mid
schedule function server:quests/rewards/_finalize 20t append
