# Auto-generated by quest reward rewrite (round 3).
playsound minecraft:entity.player.levelup player @s ~ ~ ~ 1.0 1.2
tellraw @s [{"text": "\n§a§l[Quest Complete] ", "bold": true},{"text": "Founding Fortune", "color": "white", "bold": true},{"text": "\n§eYou've amassed enough fortune to start a colony.", "bold": false},{"text": "\n§6§l✦ Reward: §e§lMinecolonies Supply Camp", "bold": false},{"text": "\n§e► Next: ", "bold": false},{"text": "Place the supply camp to found a Minecolony\n", "color": "white", "bold": false}]
tag @s add cq_reward_item_supply_camp
schedule function server:quests/rewards/_finalize 20t append
