# Auto-generated by quest reward rewrite script. Tag-based dispatcher in _finalize.mcfunction.
playsound minecraft:entity.player.levelup player @s ~ ~ ~ 1.0 1.2
tellraw @s [{"text": "\n§a§l[Quest Complete] ", "bold": true}, {"text": "Tycoon", "color": "white", "bold": true}, {"text": "\n§6§l✦ Reward: §e§lUltra Key", "bold": false}, {"text": "\n§e► Next: ", "bold": false}, {"text": "Keep stacking\n", "color": "white", "bold": false}]
# Same as reach_income_10000: gym keys moved to AdvancementHook in 0.7.63, so the
# shared cq_reward_key_ultra_1 tag would no-op. Grant directly.
gacha grant @s ultra 1
