# Auto-generated by quest reward rewrite script. Tag-based dispatcher in _finalize.mcfunction.
playsound minecraft:entity.player.levelup player @s ~ ~ ~ 1.0 1.2
tellraw @s [{"text": "\n§a§l[Quest Complete] ", "bold": true}, {"text": "Legend", "color": "white", "bold": true}, {"text": "\n§6§l✦ Reward: §e§lUltra Key", "bold": false}, {"text": "\n§e► Next: ", "bold": false}, {"text": "—\n", "color": "white", "bold": false}]
tag @s add cq_reward_key_ultra_1
schedule function server:quests/rewards/_finalize 20t append
