# Auto-generated by quest reward rewrite script. Tag-based dispatcher in _finalize.mcfunction.
playsound minecraft:entity.player.levelup player @s ~ ~ ~ 1.0 1.2
tellraw @s [{"text": "\n§a§l[Quest Complete] ", "bold": true}, {"text": "Comfortable", "color": "white", "bold": true}, {"text": "\n§6§l✦ Reward: §e§lRare Key", "bold": false}, {"text": "\n§e► Next: ", "bold": false}, {"text": "Reach $100,000 §8(Reward: §6Ultra Key§8)\n", "color": "white", "bold": false}]
# Grant the key directly. The shared cq_reward_key_rare_1 tag won't work — gym keys
# moved to AdvancementHook in 0.7.63 and _finalize.mcfunction no longer grants for
# that tag (would no-op here).
gacha grant @s rare 1
