# Auto-generated by quest reward rewrite (round 3).
playsound minecraft:entity.player.levelup player @s ~ ~ ~ 1.0 1.2
tellraw @s [{"text": "\n§a§l[Quest Complete] ", "bold": true},{"text": "Pocket Change", "color": "white", "bold": true},{"text": "\n§ePlace the Pasture Block and use the Cobbleworkers mod to put your Pokémon to work — farming, fishing, brewing, and more.", "bold": false},{"text": "\n§6§l✦ Reward: §e§lPasture Block", "bold": false},{"text": "\n§e► Next: ", "bold": false},{"text": "Win a Ranked Battle or keep earning §8(Reward: §aCommon Egg§8)\n", "color": "white", "bold": false}]
tag @s add cq_reward_item_pasture_block
schedule function server:quests/rewards/_finalize 20t append
