# Auto-generated by quest reward rewrite (round 2 — re-balanced rewards).
playsound minecraft:entity.player.levelup player @s ~ ~ ~ 1.0 1.2
tellraw @s [{"text": "\n§a§l[Quest Complete] ", "bold": true},{"text": "Welcome Home", "color": "white", "bold": true},{"text": "\n§7Reward: §f3 Red Apricorn Sprouts", "bold": false},{"text": "\n§e► Next: ", "bold": false},{"text": "Craft a Poké Ball\n", "color": "white", "bold": false}]
tag @s add cq_reward_item_apricorn_sprouts
schedule function server:quests/rewards/_finalize 20t append
