package com.cobblemonroguelite.arena

import net.minecraft.resources.ResourceLocation

/**
 * What is standing in an arena slot — either a hand-built structure or a generated platform.
 *
 * ### Why this is one type and not two nullable fields
 *
 * §2.19's band transition is detected by comparing what the run *wants* against what the run
 * *believes is standing there* ([com.cobblemonroguelite.run.RunState.stampedBuild]). Two nullable
 * fields — a template id and a palette id — would make that comparison a four-case truth table, and
 * three of the four cases are nonsense states that only exist because the type allows them. Worse,
 * a template and a palette can share a [ResourceLocation]: `ns:meadow` is a perfectly legal id for
 * both, so comparing bare ids would report "already correct" after switching between them and skip
 * the stamp that replaces the build. The tag is what makes that comparison honest.
 *
 * ### Both are supported on purpose
 *
 * §2.29 chose generation because a published build cannot ship a hand-made `.nbt` without imposing
 * somebody's taste on every server that installs it, and because the atmosphere is carried by
 * §2.24's biome repaint rather than by the structure. None of that is an argument against an owner
 * who *can* build using their own arena — it is an argument against that being the only way in. So
 * [Template] stays exactly as it was and [Palette] is the one a non-builder can author.
 */
sealed interface ArenaBuild {

    /** The id, for logs and for the resolver that will go looking for it. */
    val id: ResourceLocation

    /** A hand-built `data/<ns>/structure/<path>.nbt`, stamped by [ArenaStamper]. */
    data class Template(override val id: ResourceLocation) : ArenaBuild {
        override fun toString(): String = "template '$id'"
    }

    /**
     * A `data/<ns>/roguelite/arena_palettes/<path>.json`, generated by [ArenaGenerator].
     *
     * The id names the palette, not the arena: the same palette in two biomes produces two identical
     * platforms, and the biome repaint is what makes them read as different places.
     */
    data class Palette(override val id: ResourceLocation) : ArenaBuild {
        override fun toString(): String = "palette '$id'"
    }
}
