#!/usr/bin/env python3
"""Generate a browser-console snippet that downloads the still-missing trainer skins.

    python3 ops/gen_skin_fetch_snippet.py

Writes ops/fetch-missing-skins.js. Paste that into the browser console on any
planetminecraft.com tab; it saves every missing skin with the exact filename
install_hand_sourced_skins.py expects.

WHY THIS EXISTS RATHER THAN A curl LOOP:

planetminecraft sits behind a Cloudflare WAF that returns 403 to every request from this
machine — the site AND static.planetminecraft.com, with or without a browser user-agent
("Sorry, you have been blocked", cf-ray present). So the download cannot be automated from
the shell at all. What *can* be automated is the part inside a browser that already has a
legitimate session: a same-origin fetch carries the cookies and the WAF sees a real client.

It also removes the failure that made this necessary. Saving these pages by hand produced
28 HTML documents named `*.png` (110 KB each), because the Download button and File > Save
Page As are easy to confuse. A fetch of the download endpoint returns the PNG bytes and
nothing else, and the snippet names each file itself.

The URL list is read from ops/roguelite-missing-skins.md so there is one place to update.
"""

import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DOC = REPO / "ops/roguelite-missing-skins.md"
OUT = REPO / "ops/fetch-missing-skins.js"

# Rows look like: | `Acerola.png` | acerola | https://www.planetminecraft.com/skin/.../ |
ROW = re.compile(
    r"^\|\s*`([A-Za-z]+\.png)`\s*\|[^|]*\|\s*(https://www\.planetminecraft\.com(/skin/[^\s|]+))\s*\|",
    re.MULTILINE,
)


def main() -> None:
    text = DOC.read_text(encoding="utf-8")
    # Only the "Still needed" section: the Optional upgrades table below it lists characters
    # that already have a working skin, and re-downloading those would overwrite a good file
    # with one the operator has not chosen yet.
    start = text.index("## Still needed")
    end = text.index("## Optional upgrades")
    rows = [(name, path) for name, _full, path in ROW.findall(text[start:end])]
    if not rows:
        raise SystemExit(f"no download rows found in {DOC} — has the table format changed?")

    entries = ",\n  ".join(json.dumps([name, path]) for name, path in rows)
    OUT.write_text(
        f"""// Download the {len(rows)} missing roguelite trainer skins.
//
// 1. Open any https://www.planetminecraft.com/ page in your browser.
// 2. Open the console (Cmd-Option-J) and paste this whole file.
// 3. Chrome asks once to "allow multiple downloads" — allow it.
// 4. Move the files into ops/skin-staging/ and run:
//        python3 ops/install_hand_sourced_skins.py
//
// Generated by ops/gen_skin_fetch_snippet.py from ops/roguelite-missing-skins.md.
// Must run ON the planetminecraft origin: the fetch needs the site's own cookies, which is
// what distinguishes it from an automated request the Cloudflare WAF rejects.

(async () => {{
  const SKINS = [
  {entries}
  ];

  // A real 64x64 skin is well under 10 KB. Anything larger came back as a page rather than
  // an image, which is exactly the failure this script exists to avoid — so it is reported
  // instead of being saved under a .png name.
  const MAX_BYTES = 20000;
  const ok = [], bad = [];

  for (const [name, path] of SKINS) {{
    try {{
      const res = await fetch(path, {{ credentials: "include" }});
      if (!res.ok) {{ bad.push(`${{name}}: HTTP ${{res.status}}`); continue; }}
      const blob = await res.blob();
      if (blob.size > MAX_BYTES) {{ bad.push(`${{name}}: ${{blob.size}} bytes, not an image`); continue; }}

      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = name;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
      ok.push(`${{name}} (${{blob.size}} B)`);
    }} catch (e) {{
      bad.push(`${{name}}: ${{e.message}}`);
    }}
    // Spaced out so {len(rows)} requests in a row do not look like the thing the WAF blocks.
    await new Promise((r) => setTimeout(r, 700));
  }}

  console.log(`%cdownloaded ${{ok.length}}/${{SKINS.length}}`, "font-weight:bold");
  ok.forEach((s) => console.log("  " + s));
  if (bad.length) {{
    console.warn(`failed ${{bad.length}}:`);
    bad.forEach((s) => console.warn("  " + s));
  }}
}})();
""",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(REPO)} — {len(rows)} skins")
    for name, _ in rows:
        print(f"  {name}")


if __name__ == "__main__":
    main()
