#!/usr/bin/env python3
"""Generate [pe] AI-test variants of every real gym leader.

Reads the server-gyms trainers (skipping *_challenge), writes
aitest_<gym>_pe.json clones with ai.type=pe into the server-gym-ai-test
datapack, and emits spawn_all_pe.mcfunction that summons the whole row
(3 blocks apart along +X) tagged for /function server:aitest/cleanup.

Re-run whenever gym rosters change:

    python3 ops/gen_aitest_gyms.py
"""

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
GYMS = REPO / "modpack/server-overrides/datapacks/server-gyms/data/rctmod/trainers"
AITEST = REPO / "modpack/server-overrides/datapacks/server-gym-ai-test"
TRAINERS_OUT = AITEST / "data/rctmod/trainers"
FUNCTIONS_OUT = AITEST / "data/server/function/aitest"

SPACING = 3  # blocks between leaders along +X


def _tera_keys(obj, path="") -> list[str]:
    """Paths of any dict keys mentioning tera (canTera, teraType, teraTarget...)."""
    found = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            if "tera" in k.lower():
                found.append(f"{path}/{k}")
            found += _tera_keys(v, f"{path}/{k}")
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            found += _tera_keys(v, f"{path}[{i}]")
    return found


def main() -> None:
    # hard-mode roster when one exists (the ShepskyDad L50 teams), else base
    gym_files = sorted(
        (
            challenge if (challenge := p.with_name(f"{p.stem}_challenge.json")).exists() else p
        )
        for p in GYMS.glob("gym_*.json")
        if not p.stem.endswith("_challenge")
    )
    assert gym_files, f"no gym trainers found in {GYMS}"

    lines = [
        "# Spawn [pe] variants of ALL gym leaders at caller's position, "
        f"{SPACING} blocks apart along +X.",
        "# Generated by ops/gen_aitest_gyms.py — do not edit by hand.",
        "# Cleanup: /function server:aitest/cleanup",
        "",
        "kill @e[type=rctmod:trainer,tag=aitest.variant.pe_all]",
        "",
    ]

    names = []
    for i, path in enumerate(gym_files):
        trainer = json.loads(path.read_text())
        display = trainer["name"].replace("Gym Leader ", "").replace("Champion ", "")
        names.append(display)
        trainer["name"] = f"AI Test [pe]: {display}"
        trainer["ai"] = {"type": "pe", "data": {}}

        # Terastallization is disabled server-wide. Source files keep tera only
        # in ai.data (replaced above), but guard against future hard-mode teams
        # introducing it elsewhere (teraType on mons etc.). Key-based check —
        # substrings false-positive on e.g. the "waterabsorb" ability.
        leaks = _tera_keys(trainer)
        assert not leaks, f"{path.name}: tera config leaked: {leaks}"

        trainer_id = f"aitest_{path.stem.removesuffix('_challenge')}_pe"
        out = TRAINERS_OUT / f"{trainer_id}.json"
        out.write_text(json.dumps(trainer, indent=2) + "\n")

        offset = i * SPACING
        sel = (
            f'@e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,'
            f'nbt={{TrainerId:"{trainer_id}"}}]'
        )
        lines += [
            f"# {trainer['name']}  (+{offset}x)",
            f"execute at @s positioned ^{offset} ^ ^ run rctmod trainer summon_persistent {trainer_id}",
            f"execute at @s positioned ^{offset} ^ ^ run tag {sel} add aitest",
            f"execute at @s positioned ^{offset} ^ ^ run tag {sel} add aitest.variant.pe_all",
            f"execute at @s positioned ^{offset} ^ ^ run data merge entity {sel} {{Invulnerable:1b,PersistenceRequired:1b}}",
            "",
        ]

    lines.append(
        'tellraw @s [{"text":"§a✓ Spawned AI Test [pe] row: '
        + f'{len(gym_files)} leaders","bold":true}},'
        + '{"text":"\\n§7Cleanup: §f/function server:aitest/cleanup"}]'
    )

    out_fn = FUNCTIONS_OUT / "spawn_all_pe.mcfunction"
    out_fn.write_text("\n".join(lines) + "\n")
    print(f"wrote {len(gym_files)} trainer variants to {TRAINERS_OUT}")
    print(f"wrote {out_fn}")
    print("leaders:", ", ".join(names))


if __name__ == "__main__":
    main()
