#!/usr/bin/env python3
"""Generate [pe] AI-test variants of every real gym leader.

Reads the server-gyms trainers (skipping *_challenge), writes
aitest_<gym>_pe.json clones with ai.type=pe into the server-gym-ai-test
datapack, and emits spawn_all_pe.mcfunction that summons the whole row
(3 blocks apart along +X) tagged for /function server:aitest/cleanup.

Re-run whenever gym rosters change:

    python3 ops/gen_aitest_gyms.py
"""

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
GYMS = REPO / "modpack/server-overrides/datapacks/server-gyms/data/rctmod/trainers"
AITEST = REPO / "modpack/server-overrides/datapacks/server-gym-ai-test"
TRAINERS_OUT = AITEST / "data/rctmod/trainers"
FUNCTIONS_OUT = AITEST / "data/server/function/aitest"

SPACING = 3  # blocks between leaders along +X


def _tera_keys(obj, path="") -> list[str]:
    """Paths of any dict keys mentioning tera (canTera, teraType, teraTarget...)."""
    found = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            if "tera" in k.lower():
                found.append(f"{path}/{k}")
            found += _tera_keys(v, f"{path}/{k}")
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            found += _tera_keys(v, f"{path}[{i}]")
    return found


def main() -> None:
    # hard-mode roster when one exists (the ShepskyDad L50 teams), else base
    gym_files = sorted(
        (
            challenge if (challenge := p.with_name(f"{p.stem}_challenge.json")).exists() else p
        )
        for p in GYMS.glob("gym_*.json")
        if not p.stem.endswith("_challenge")
    )
    assert gym_files, f"no gym trainers found in {GYMS}"

    names = []
    chunk_size = 3
    chunks: list[list[tuple[str, str]]] = []  # [(trainer_id, display), ...]
    for i, path in enumerate(gym_files):
        trainer = json.loads(path.read_text())
        display = trainer["name"].replace("Gym Leader ", "").replace("Champion ", "")
        names.append(display)
        trainer["name"] = f"AI Test [pe]: {display}"
        trainer["ai"] = {"type": "pe", "data": {}}

        # Terastallization is disabled server-wide. Source files keep tera only
        # in ai.data (replaced above), but guard against future hard-mode teams
        # introducing it elsewhere (teraType on mons etc.). Key-based check —
        # substrings false-positive on e.g. the "waterabsorb" ability.
        leaks = _tera_keys(trainer)
        assert not leaks, f"{path.name}: tera config leaked: {leaks}"

        trainer_id = f"aitest_{path.stem.removesuffix('_challenge')}_pe"
        out = TRAINERS_OUT / f"{trainer_id}.json"
        out.write_text(json.dumps(trainer, indent=2) + "\n")

        if i % chunk_size == 0:
            chunks.append([])
        chunks[-1].append((trainer_id, display))

    # One spawn function per chunk of 3 — fighting 24 leaders in one row was
    # unwieldy. Each spawn_N replaces only its own chunk; cleanup removes all.
    for n, chunk in enumerate(chunks, 1):
        chunk_tag = f"aitest.chunk{n}"
        chunk_names = ", ".join(d for _, d in chunk)
        lines = [
            f"# Spawn AI-test chunk {n}/{len(chunks)}: {chunk_names}",
            "# Generated by ops/gen_aitest_gyms.py — do not edit by hand.",
            "# Cleanup all: /function server:aitest/cleanup",
            "",
            f"kill @e[type=rctmod:trainer,tag={chunk_tag}]",
            "",
        ]
        for j, (trainer_id, display) in enumerate(chunk):
            offset = j * SPACING
            sel = (
                f'@e[type=rctmod:trainer,distance=..5,limit=1,sort=nearest,'
                f'nbt={{TrainerId:"{trainer_id}"}}]'
            )
            lines += [
                f"# {display}  (+{offset}x)",
                f"execute at @s positioned ^{offset} ^ ^ run rctmod trainer summon_persistent {trainer_id}",
                f"execute at @s positioned ^{offset} ^ ^ run tag {sel} add aitest",
                f"execute at @s positioned ^{offset} ^ ^ run tag {sel} add {chunk_tag}",
                f"execute at @s positioned ^{offset} ^ ^ run data merge entity {sel} {{Invulnerable:1b,PersistenceRequired:1b}}",
                "",
            ]
        nxt = (
            f'{{"text":"\\n§7Next: §f/function server:aitest/spawn_{n + 1}"}}'
            if n < len(chunks)
            else '{"text":"\\n§7That was the last chunk."}'
        )
        lines.append(
            f'tellraw @s [{{"text":"§a✓ Chunk {n}/{len(chunks)}: {chunk_names}","bold":true}},'
            + nxt
            + ',{"text":"\\n§7Cleanup: §f/function server:aitest/cleanup"}]'
        )
        (FUNCTIONS_OUT / f"spawn_{n}.mcfunction").write_text("\n".join(lines) + "\n")

    stale = FUNCTIONS_OUT / "spawn_all_pe.mcfunction"
    if stale.exists():
        stale.unlink()

    print(f"wrote {len(gym_files)} trainer variants to {TRAINERS_OUT}")
    print(f"wrote {len(chunks)} spawn chunks (spawn_1..spawn_{len(chunks)})")
    print("leaders:", ", ".join(names))


if __name__ == "__main__":
    main()
