name = "Cobblemon Server"
author = "Harris Spahic"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce6cec86e0811ec5838837634dc1d792825391ad87c26a7066110afc4a83f655"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
