name = "Cobblemon Server"
author = "Harris Spahic"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b513a0157109a366e447234ae9dfb272d8a42a2ccbd1ec020524e7a0ef060542"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
