name = "Cobblemon Server"
author = "Harris Spahic"
version = "0.7.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85999625718785b4340ebac4310747fe08ad96eab7c02f91aaa103b593798cff"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
